Repository edu-pi/Backend-Meta-Server, pull requests merged in 2024-09, with the labels that each got.

#14 [deploy] cicd.yml 추가
  .github/workflows/cicd.yml
  edupi_db.json
Labels: BE, deployment

#16 [#13]deploy: 배포를 위한 환경설정
  .github/workflows/cicd-dev.yml
  .github/workflows/cicd.yml
  .github/workflows/pull-request-build.yml
  .gitignore
  Dockerfile
  build.gradle
  src/main/java/soma/haeya/edupi_db/member/controller/HealthCheckController.java
  src/main/resources/.gitkeep
  src/test/java/soma/haeya/edupi_db/member/controller/MemberControllerTest.java
Labels: BE, deployment

#17 [#15]feat: Exception 이름 변경, 회원 가입 성공 때 리턴 값 변경
  src/main/java/soma/haeya/edupi_db/GlobalExceptionHandler.java
  src/main/java/soma/haeya/edupi_db/member/controller/MemberController.java
  src/main/java/soma/haeya/edupi_db/member/dto/response/ErrorResponse.java
  src/main/java/soma/haeya/edupi_db/member/dto/response/SignupResponse.java
  src/main/java/soma/haeya/edupi_db/member/dto/response/SuccessResponse.java
  src/main/java/soma/haeya/edupi_db/member/exception/GlobalExceptionHandler.java
  src/main/java/soma/haeya/edupi_db/member/exception/InvalidInputException.java
  src/main/java/soma/haeya/edupi_db/member/exception/ServerException.java
  src/main/java/soma/haeya/edupi_db/member/exception/UserFriendlyException.java
  src/main/java/soma/haeya/edupi_db/member/service/MemberService.java
  src/test/java/soma/haeya/edupi_db/member/controller/MemberControllerTest.java
  src/test/java/soma/haeya/edupi_db/member/service/MemberServiceTest.java
Labels: BE

#20 [#19]Feat: 클래스룸 생성 기능 추가
  src/main/java/soma/haeya/edupi_db/classroom/controller/ClassroomController.java
  src/main/java/soma/haeya/edupi_db/classroom/domain/Classroom.java
  src/main/java/soma/haeya/edupi_db/classroom/exception/ClassroomExceptionHandler.java
  src/main/java/soma/haeya/edupi_db/classroom/models/request/CreateClassroomRequest.java
  src/main/java/soma/haeya/edupi_db/classroom/repository/ClassroomRepository.java
  src/main/java/soma/haeya/edupi_db/classroom/service/ClassroomService.java
  src/main/java/soma/haeya/edupi_db/common/controller/HealthCheckController.java
  src/main/java/soma/haeya/edupi_db/common/exception/DbServerException.java
  src/main/java/soma/haeya/edupi_db/common/exception/ExceptionLogger.java
  src/main/java/soma/haeya/edupi_db/common/models/response/DefaultErrorResponse.java
  src/main/java/soma/haeya/edupi_db/member/GlobalExceptionHandler.java
  src/main/java/soma/haeya/edupi_db/member/dto/response/ErrorResponse.java
Labels: BE, feat

#21 [#18]feat: Swagger 통합 위한 설정
  build.gradle
  src/main/java/soma/haeya/edupi_db/classroom/controller/ClassroomController.java
  src/main/java/soma/haeya/edupi_db/classroom/controller/ClassroomSpecification.java
  src/main/java/soma/haeya/edupi_db/common/controller/HealthCheckController.java
  src/main/java/soma/haeya/edupi_db/member/config/OpenApiConfig.java
  src/main/java/soma/haeya/edupi_db/member/controller/MemberController.java
  src/main/java/soma/haeya/edupi_db/member/controller/MemberSpecification.java
  src/main/java/soma/haeya/edupi_db/member/service/MemberService.java
  src/test/java/soma/haeya/edupi_db/member/controller/MemberControllerTest.java
  src/test/java/soma/haeya/edupi_db/member/service/MemberServiceTest.java
Labels: BE

#31 [#30]feat: 이메일 인증 - 계정 활성화
  src/main/java/soma/edupi/db/account/controller/AccountController.java
  src/main/java/soma/edupi/db/account/controller/AccountSpecification.java
  src/main/java/soma/edupi/db/account/domain/Account.java
  src/main/java/soma/edupi/db/account/models/request/EmailRequest.java
  src/main/java/soma/edupi/db/account/models/response/AccountActivateResponse.java
  src/main/java/soma/edupi/db/account/service/AccountService.java
  src/test/java/soma/edupi/db/account/service/AccountServiceTest.java
Labels: BE, feat

#33 [#32]feat: 내가 등록한 클래스룸 리스트 조회
  src/main/java/soma/edupi/db/classroom/controller/ClassroomController.java
  src/main/java/soma/edupi/db/classroom/models/response/ClassroomResponse.java
  src/main/java/soma/edupi/db/classroom/models/response/MyClassroomsResponse.java
  src/main/java/soma/edupi/db/classroom/repository/ClassroomQueryRepository.java
  src/main/java/soma/edupi/db/classroom/repository/ClassroomQueryRepositoryImpl.java
  src/main/java/soma/edupi/db/classroom/service/ClassroomService.java
Labels: BE, feat

#39 [#38]refactor: Mapping path 수정
  src/main/java/soma/edupimeta/account/AccountController.java
  src/main/java/soma/edupimeta/classroom/ClassroomController.java
Labels: BE, refactor
